### ISSUE TITLE
Are You Krishna

### ISSUE THREAD

**Issue by Hobby-Dev-0** [LEGEND-AI/LEGENDUSERBOT#12]

**Comment by LEGEND-AI** [comment]
@Hobby-Dev-0 hmm Krishna Hi Hu

Old wala scam ho gya h

**Comment by Hobby-Dev-0** [comment]
> @Hobby-Dev-0 hmm Krishna Hi Hu
> 
> Old wala scam ho gya h

@LEGEND-AI BHai Tlegram username do

**Comment by LEGEND-AI** [comment]
@Hobby-Dev-0 Telegram Username @LEGENDBOY_XD

https://telegram.me/LegendBoy_XD

**Comment by Ryoishin** [comment]
> _No description provided._

Hello Bro Me Shivansh Bc Apna Telegram Username De

**Comment by Hobby-Dev-0** [comment]
@Ryoishin Tu hi dede main telegram pr nhi hu

**Comment by Hobby-Dev-0** [comment]
main aayunga to msg kr dunga

**Comment by LEGEND-AI** [comment]
@Hobby-Dev-0 Spot Death In telegram 🤣🤣

**Comment by Hobby-Dev-0** [comment]
> @Hobby-Dev-0 Spot Death In telegram 🤣🤣

Kya Matlab

**Comment by LEGEND-AI** [comment]
@Hobby-Dev-0 

https://github.com/LEGEND-AI/LEGENDUSERBOT/blob/master/userbot/plugins/archive.py#L209

Check This Is This Will work

Check 209 Or 210
